### ISSUE TITLE
"note on" events in an invalid sequence

### ISSUE THREAD

**Issue by maximedupre** [chrisguttandin/midi-json-parser#251]
For this file: https://ufile.io/r085t

When decoding, I can get two "note on" events for the same midi note before getting a "note off" event (for the same midi note). I don't think this is a valid behaviour.

However this file is likely a valid MIDI file, since it plays in DAWS.

Cheers!

**Comment by chrisguttandin** [comment]
Hi @maximedupre, can you please point me to the event which you are talking about? I parsed the file but it is too large to find the duplicate events manually. :-)

Also I don't really know if this behavior is invalid. It might make no sense but as far as I know the MIDI spec does not prohibit this. Maybe your DAW does just ignore duplicate events.

Anyway, I will take a look to make sure the parsing is correct. Can you please tell me the note number of the note in question? That should make it easier to spot the duplicate noteOn events.

Many thanks in advance.

**Comment by maximedupre** [comment]
Hey! Here are logs of the "note on" events and "note off" events in the same order than the MIDI file:

![screen shot 2019-02-19 at 9 17 58 pm](https://user-images.githubusercontent.com/5158181/53061630-2a39af00-348c-11e9-8d44-099ac1377134.png)

Like you said, the MIDI file is quite big and there are multiple instances of this weird behaviour:

![screen shot 2019-02-19 at 9 19 00 pm](https://user-images.githubusercontent.com/5158181/53061670-4ccbc800-348c-11e9-8cd3-fa88ba06620a.png)

This sequence of events makes little sense to me, but maybe you are right, there might be nothing that prohibits this order, in which case I would have to adapt my logic like you suggested.

Please let me know what you think of this :). Thanks to you!

**Comment by chrisguttandin** [comment]
Hi @maximedupre, I just realized which track this MIDI file encodes and I would argue that in a track of that artist anything is possible. :-) One of my favorite tracks from him by the way.

When I count the overall number of noteOn and noteOff events for the note number 62 I get 89 events for both categories. This implies that there is a nodeOff event for every nodeOn event. All events are on channel zero. Is it possible that the file was historically for more than one channel and somehow got collapsed to one channel at some point?

I'm curious though what does a DAW like Ableton do when you import the file?

**Comment by maximedupre** [comment]
Hehe, sorry I know nothing about this author of this track, it's a file a coworker gave to me =).

There is indeed a "note off" event for each "note on" events, but as you know. the problem is in the ordering of those events. If, like my screenshot shows, 2 "note on" events for number 62 occur in a row, how do I know which "note on" event is paired with the next "note off" event? Let me know if I am missing something.

Also I really don't know if all channels got collapsed into channel 0.

Everything works as expected in Ableton:
<img width="1141" alt="screen shot 2019-02-22 at 11 32 53 am" src="https://user-images.githubusercontent.com/5158181/53256364-af43e480-3695-11e9-9550-27f9137100f3.png">


Thanks :)!

**Comment by chrisguttandin** [comment]
Hi @maximedupre,

I filtered the JSON output that it only contains the noteOn/Off events for noteNumber 62. I also converted the delta values to seconds which hopefully makes it easier to identify the corresponding notes in the piano roll of a DAW.

<details>
<summary>condensed JSON for note 62</summary>
<p>

```json
[
    {
        "type": "on",
        "time": 0
    },
    {
        "type": "off",
        "time": 0.789473
    },
    {
        "type": "on",
        "time": 65.32889075
    },
    {
        "type": "off",
        "time": 66.31573199999998
    },
    {
        "type": "on",
        "time": 66.90783675
    },
    {
        "type": "off",
        "time": 67.894678
    },
    {
        "type": "on",
        "time": 68.48678275
    },
    {
        "type": "off",
        "time": 69.473624
    },
    {
        "type": "on",
        "time": 70.06572874999999
    },
    {
        "type": "off",
        "time": 71.05256999999999
    },
    {
        "type": "on",
        "time": 71.64467475
    },
    {
        "type": "off",
        "time": 72.631516
    },
    {
        "type": "on",
        "time": 73.22362075
    },
    {
        "type": "off",
        "time": 74.21046199999999
    },
    {
        "type": "on",
        "time": 74.80256675
    },
    {
        "type": "off",
        "time": 75.789408
    },
    {
        "type": "on",
        "time": 76.38151275
    },
    {
        "type": "off",
        "time": 77.368354
    },
    {
        "type": "on",
        "time": 80.526246
    },
    {
        "type": "off",
        "time": 80.72361425
    },
    {
        "type": "on",
        "time": 80.72361425
    },
    {
        "type": "off",
        "time": 80.9209825
    },
    {
        "type": "on",
        "time": 80.9209825
    },
    {
        "type": "off",
        "time": 81.11835075
    },
    {
        "type": "on",
        "time": 81.11835075
    },
    {
        "type": "off",
        "time": 81.315719
    },
    {
        "type": "on",
        "time": 86.84203
    },
    {
        "type": "off",
        "time": 87.03939825
    },
    {
        "type": "on",
        "time": 87.03939825
    },
    {
        "type": "off",
        "time": 87.2367665
    },
    {
        "type": "on",
        "time": 87.2367665
    },
    {
        "type": "off",
        "time": 87.43413475
    },
    {
        "type": "on",
        "time": 87.43413475
    },
    {
        "type": "off",
        "time": 87.631503
    },
    {
        "type": "on",
        "time": 93.157814
    },
    {
        "type": "off",
        "time": 93.35518225
    },
    {
        "type": "on",
        "time": 93.35518225
    },
    {
        "type": "off",
        "time": 93.5525505
    },
    {
        "type": "on",
        "time": 93.5525505
    },
    {
        "type": "off",
        "time": 93.74991874999999
    },
    {
        "type": "on",
        "time": 93.74991874999999
    },
    {
        "type": "off",
        "time": 93.947287
    },
    {
        "type": "on",
        "time": 99.473598
    },
    {
        "type": "off",
        "time": 99.67096624999999
    },
    {
        "type": "on",
        "time": 99.67096624999999
    },
    {
        "type": "off",
        "time": 99.8683345
    },
    {
        "type": "on",
        "time": 99.8683345
    },
    {
        "type": "off",
        "time": 100.06570275
    },
    {
        "type": "on",
        "time": 100.06570275
    },
    {
        "type": "off",
        "time": 100.263071
    },
    {
        "type": "on",
        "time": 102.63148999999999
    },
    {
        "type": "off",
        "time": 103.42096299999999
    },
    {
        "type": "on",
        "time": 103.42096299999999
    },
    {
        "type": "on",
        "time": 103.61833124999998
    },
    {
        "type": "off",
        "time": 103.8156995
    },
    {
        "type": "on",
        "time": 103.8156995
    },
    {
        "type": "off",
        "time": 104.01306774999999
    },
    {
        "type": "on",
        "time": 104.01306774999999
    },
    {
        "type": "off",
        "time": 104.21043599999999
    },
    {
        "type": "off",
        "time": 104.21043599999999
    },
    {
        "type": "on",
        "time": 104.80254075
    },
    {
        "type": "off",
        "time": 105.789382
    },
    {
        "type": "on",
        "time": 106.57885499999999
    },
    {
        "type": "on",
        "time": 106.77622325
    },
    {
        "type": "off",
        "time": 106.9735915
    },
    {
        "type": "on",
        "time": 106.9735915
    },
    {
        "type": "off",
        "time": 107.17095975
    },
    {
        "type": "on",
        "time": 107.17095975
    },
    {
        "type": "off",
        "time": 107.36832799999999
    },
    {
        "type": "off",
        "time": 107.36832799999999
    },
    {
        "type": "on",
        "time": 107.96043275
    },
    {
        "type": "off",
        "time": 108.15780099999999
    },
    {
        "type": "on",
        "time": 108.15780099999999
    },
    {
        "type": "off",
        "time": 108.35516924999999
    },
    {
        "type": "on",
        "time": 108.35516924999999
    },
    {
        "type": "off",
        "time": 108.55253749999999
    },
    {
        "type": "on",
        "time": 108.55253749999999
    },
    {
        "type": "off",
        "time": 108.74990575
    },
    {
        "type": "on",
        "time": 108.74990575
    },
    {
        "type": "off",
        "time": 108.947274
    },
    {
        "type": "on",
        "time": 109.736747
    },
    {
        "type": "on",
        "time": 109.93411524999999
    },
    {
        "type": "off",
        "time": 110.13148349999999
    },
    {
        "type": "on",
        "time": 110.13148349999999
    },
    {
        "type": "off",
        "time": 110.32885174999998
    },
    {
        "type": "on",
        "time": 110.32885174999998
    },
    {
        "type": "off",
        "time": 110.52622
    },
    {
        "type": "off",
        "time": 110.52622
    },
    {
        "type": "on",
        "time": 111.11832475
    },
    {
        "type": "off",
        "time": 111.315693
    },
    {
        "type": "on",
        "time": 111.315693
    },
    {
        "type": "off",
        "time": 111.51306124999999
    },
    {
        "type": "on",
        "time": 111.51306124999999
    },
    {
        "type": "off",
        "time": 111.7104295
    },
    {
        "type": "on",
        "time": 111.7104295
    },
    {
        "type": "off",
        "time": 111.90779775
    },
    {
        "type": "on",
        "time": 111.90779775
    },
    {
        "type": "off",
        "time": 112.105166
    },
    {
        "type": "on",
        "time": 112.894639
    },
    {
        "type": "on",
        "time": 113.09200725
    },
    {
        "type": "off",
        "time": 113.28937549999999
    },
    {
        "type": "on",
        "time": 113.28937549999999
    },
    {
        "type": "off",
        "time": 113.48674374999999
    },
    {
        "type": "on",
        "time": 113.48674374999999
    },
    {
        "type": "off",
        "time": 113.684112
    },
    {
        "type": "off",
        "time": 113.684112
    },
    {
        "type": "on",
        "time": 115.26305799999999
    },
    {
        "type": "off",
        "time": 116.05253099999999
    },
    {
        "type": "on",
        "time": 116.05253099999999
    },
    {
        "type": "on",
        "time": 116.24989924999998
    },
    {
        "type": "off",
        "time": 116.44726749999998
    },
    {
        "type": "on",
        "time": 116.44726749999998
    },
    {
        "type": "off",
        "time": 116.64463574999999
    },
    {
        "type": "on",
        "time": 116.64463574999999
    },
    {
        "type": "off",
        "time": 116.84200399999999
    },
    {
        "type": "off",
        "time": 116.84200399999999
    },
    {
        "type": "on",
        "time": 117.43410875
    },
    {
        "type": "off",
        "time": 118.42094999999999
    },
    {
        "type": "on",
        "time": 119.21042299999999
    },
    {
        "type": "on",
        "time": 119.40779124999999
    },
    {
        "type": "off",
        "time": 119.6051595
    },
    {
        "type": "on",
        "time": 119.6051595
    },
    {
        "type": "off",
        "time": 119.80252775
    },
    {
        "type": "on",
        "time": 119.80252775
    },
    {
        "type": "off",
        "time": 119.99989599999999
    },
    {
        "type": "off",
        "time": 119.99989599999999
    },
    {
        "type": "on",
        "time": 120.59200075
    },
    {
        "type": "off",
        "time": 120.789369
    },
    {
        "type": "on",
        "time": 120.789369
    },
    {
        "type": "off",
        "time": 120.98673724999999
    },
    {
        "type": "on",
        "time": 120.98673724999999
    },
    {
        "type": "off",
        "time": 121.18410549999999
    },
    {
        "type": "on",
        "time": 121.18410549999999
    },
    {
        "type": "off",
        "time": 121.38147374999998
    },
    {
        "type": "on",
        "time": 121.38147374999998
    },
    {
        "type": "off",
        "time": 121.578842
    },
    {
        "type": "on",
        "time": 122.36831499999998
    },
    {
        "type": "on",
        "time": 122.56568324999999
    },
    {
        "type": "off",
        "time": 122.76305149999999
    },
    {
        "type": "on",
        "time": 122.76305149999999
    },
    {
        "type": "off",
        "time": 122.96041974999999
    },
    {
        "type": "on",
        "time": 122.96041974999999
    },
    {
        "type": "off",
        "time": 123.157788
    },
    {
        "type": "off",
        "time": 123.157788
    },
    {
        "type": "on",
        "time": 123.74989275
    },
    {
        "type": "off",
        "time": 123.947261
    },
    {
        "type": "on",
        "time": 123.947261
    },
    {
        "type": "off",
        "time": 124.14462925
    },
    {
        "type": "on",
        "time": 124.14462925
    },
    {
        "type": "off",
        "time": 124.34199749999999
    },
    {
        "type": "on",
        "time": 124.34199749999999
    },
    {
        "type": "off",
        "time": 124.53936575
    },
    {
        "type": "on",
        "time": 124.53936575
    },
    {
        "type": "off",
        "time": 124.736734
    },
    {
        "type": "on",
        "time": 125.526207
    },
    {
        "type": "on",
        "time": 125.72357525
    },
    {
        "type": "off",
        "time": 125.92094349999999
    },
    {
        "type": "on",
        "time": 125.92094349999999
    },
    {
        "type": "off",
        "time": 126.11831174999999
    },
    {
        "type": "on",
        "time": 126.11831174999999
    },
    {
        "type": "off",
        "time": 126.31567999999999
    },
    {
        "type": "off",
        "time": 126.31567999999999
    },
    {
        "type": "on",
        "time": 146.841978
    },
    {
        "type": "off",
        "time": 147.2367145
    },
    {
        "type": "on",
        "time": 147.631451
    },
    {
        "type": "off",
        "time": 148.0261875
    },
    {
        "type": "on",
        "time": 149.99987
    },
    {
        "type": "off",
        "time": 150.39460649999998
    },
    {
        "type": "on",
        "time": 150.789343
    },
    {
        "type": "off",
        "time": 151.1840795
    },
    {
        "type": "on",
        "time": 153.94723499999998
    },
    {
        "type": "off",
        "time": 154.34197149999997
    },
    {
        "type": "on",
        "time": 157.10512699999998
    },
    {
        "type": "off",
        "time": 157.49986349999998
    },
    {
        "type": "on",
        "time": 194.01298974999997
    },
    {
        "type": "off",
        "time": 194.60509449999998
    },
    {
        "type": "on",
        "time": 197.17088175
    },
    {
        "type": "off",
        "time": 197.7629865
    }
]
```

</p>
</details>

The first strange sequence of events happens after 103.42096299999999 seconds. As you mentioned their are two adjacent noteOn events (103.42096299999999, 103.61833124999998). The next noteOff event is at 103.8156995 seconds.

I wonder what Ableton does in this case. Does it display a note from 103.42096299999999 to 103.8156995 or does it insert an additional stop event at 103.61833124999998 to have two consecutive notes?

**Comment by maximedupre** [comment]
I realize now by looking at your filtered data that the only way to alternative "note on" and "note off" events would be to have negative deltas. Is it possible to have negative deltas?

The DAW seems to display notes like this:

103.42096299999999 to 103.8156995
103.61833124999998 to 104.01306774999999
103.8156995 to 104.21043599999999
104.01306774999999 to 104.21043599999999

It looks like the DAW compensates for this weirdly formed MIDI file and associates the first instance of a "note on" event with the first instance of a "note off" event - the second instance of a "note on" event with the second instance of a "note off" event, etc

However this does not make sense, because it would mean that, for example, "note 103.61833124999998" could never end before "note 103.42096299999999". This limitation seems silly to me.

So here are the three possible conclusions I can think of:
* There is a possibility to have negative deltas to properly match  "note on" and "note off" events
* There is a bug in the parsing of the midi file
* Having two adjacent "note on" events does not render the MIDI invalid, but at the same it not a standardized behaviour, so the only way to map "note on" and "note off" events is to guess.

What do you think?

**Comment by chrisguttandin** [comment]
Hi @maximedupre, thanks again for following up on this issue.

I think in the spirit of separation of concerns it would be a good idea to create another package. That could be named midi-file-sanitizer and it would be responsible for turning an arbitrary sequence of noteOn/Off events into a sequence which only contains pairs of noteOn/Off events. It could also be responsible to check some other stuff. Checking that every track ends with an endOfTrack event, for example, could be another check.

The reason why I think this should be a separate package is that some people may prefer to decode MIDI files as they are even if the sequence of events doesn't really makes sense.

Another reason would be that midi-file-sanitizer would need to accept some configuration as it isn't really obvious what should be done with orphaned noteOn/Off events.

Do you think that makes sense?

**Comment by maximedupre** [comment]
Hi Chris, I appreciate your replies :).

I like your idea of creating a separate midi validator library!

> The reason why I think this should be a separate package is that some people may prefer to decode MIDI files as they are even if the sequence of events doesn't really makes sense.

If I understand, you are saying that the `midi-json-parser` library has no bug and that the MIDI file makes inherently no sense at some places? I'm not saying it does have a bug, but have you discarded the idea that the MIDI file is in fact correct, but that the parsing causes some bugs, hence the parts of it that make no sense?

Please let me know :).

**Comment by chrisguttandin** [comment]
Well, this is only true until someone proofs I'm wrong. But for now I believe that the file is parsed correctly and just contains some noteOn and noteOff events which don't really make sense.

Just to double check, I also parsed the file with [midi-converter](https://github.com/mobyvb/midi-converter) and it returns the same sequence of events.

**Comment by maximedupre** [comment]
Oh nice catch! Well then let's consider this ticket as closed.

Thanks Christ!
