### ISSUE TITLE
NoteOff when it is NoteOn ?

### ISSUE THREAD

**Issue by ctrl-alt-d** [chrisguttandin/midi-json-parser#254]
Hi Mr @chrisguttandin ,

first of all, congrats about your work and your library. I want to use it to create music visualizations with p5*js.

Ok, I have added `midi-json-parser` to my npm project and I have a little problem, I think the library is misunderstanding `NoteOn` events:

![selection_435](https://user-images.githubusercontent.com/3105983/53275772-a89c8800-36fc-11e9-85a7-fbe2d0772634.png)

*Notice this all `NoteOff` events they have "Velocity" property.*

You can found the picture midi file at  https://github.com/ctrl-alt-d/A_F_NO7_01_viz/tree/feature/skeleton/scores ( it is downloaded from musescore ).

Best regards,
dani.

**Comment by chrisguttandin** [comment]
bon dia @ctrl-alt-d,

thanks for reporting this issue. There was a problem with MIDI files which used running status. It should be fixed now with version v6.0.21.

Please let me know if you encounter any other issues.

**Comment by ctrl-alt-d** [comment]
goedemiddag @chrisguttandin ,

I tried new version and runs like a charm, congrats.

We are in touch!

Best regards from Catalonia,
dani herrera.
