### ISSUE TITLE
I miss midi information

### ISSUE THREAD

**Issue by ctrl-alt-d** [chrisguttandin/midi-json-parser#255]
Hi Mr @chrisguttandin ,

after parse file, I miss two relevant midi data values which are present on midi file but not on JSON:

* `duration`: for how long this note should be played.
* `time`: at what time (from beginning) this note starts.

Something like this:

Note 0:
* channel: 0
* delta: 0
* time: 0                   <--- I miss this
* noteOn: 
   * noteNumber: 81
   * velocity: 80
   * duration: 0.3145833333333333                   <--- I miss this

Note 1:
* channel: 0
* delta: 9
* time: 0.3333333333333333                   <--- I miss this
* noteOn: 
   * noteNumber: 76
   * velocity: 80
   * duration: 0.3145833333333333                   <--- I miss this

Where can I found this information on JSON?

Thanks,

dani herrera.

**Comment by chrisguttandin** [comment]
Hi @ctrl-alt-d,

this module is just meant to transfer the data structure of a MIDI file into JSON. Both values you are looking for are not present in a MIDI file. However it is possible to compute them.

You can use the `delta` of each event to compute the `time` you are looking for. In combination with the division of a file and the microSecondsPerBeat the formula somehow looks like this:

```
delta * (microsecondsPerBeat / division)
```

I'm the author of utility library called [`midi-file-slicer`](https://github.com/chrisguttandin/midi-file-slice). It's meant to slice MIDI files but you can also use it to just compute the time value you're after. This is how you would do it:

```js
import { MidiFileSlicer } from 'midi-file-slicer';

const midiFileSlicer = midiFileSlicer({ json });

console.log(midiFileSlicer.slice(0, Number.POSITIVE_INFINITY));
```
To compute the duration of a noteOn event you can scan the MIDI file for the next noteOff event with the same noteNumber and subtract their deltas from each other.

```js
const durationInTicks = noteOffEvent.delta - noteOnEvent.delta;
```

I hope this helps.

**Comment by ctrl-alt-d** [comment]
Hi @chrisguttandin,

thanks a lot again for your fast reply. I will try both methods.

We are in touch,
dani.

**Comment by stephaneeybert** [comment]
How to find these two events used to compute this duration ? Are they sequentially following each other ? Do we have to be carefull with any track or channel number ?

**Comment by chrisguttandin** [comment]
Hi @stephaneeybert,

you are right the delta is only the time between consecutive events. You can't be sure that a noteOn event is directly followed by a noteOff event. Maybe there are some other events in between. That's why using the delta of the noteOf event may sometimes work but not always.

A brute-force approach would be to compute the absolute offsets by piping the whole file through a `MidiFileSlicer` first, like this:

```javascript
import { MidiFileSlicer } from 'midi-file-slicer';

const midiFileSlicer = new MidiFileSlicer({ json });
const timedMidiEvents = midiFileSlicer.slice(0, Number.POSITIVE_INFINITY);
```

You can then filter the array to make sure you end up only with full notes (combined noteOn and noteOff events) which do have three properties (noteNumber, time and duration).

```javascript
const [ notes ] = timedMidiEvents
    .reduce(([ notes, noteOnEvents ], { event, time }) => {
        if ('noteOn' in event) {
            const { noteNumber } = event.noteOn;
            const partialNote = { noteNumber, time };

            notes.push(partialNote);
            noteOnEvents.set(noteNumber, partialNote);
        } else if ('noteOff' in event) {
            const { noteNumber } = event.noteOff;
            const partialNote = noteOnEvents.get(noteNumber);

            partialNote.duration = time - partialNote.time;
        }

        return [ notes, noteOnEvents ];
    }, [ [ ], new Map() ]);
```

The snippet above is of course simplifying things a bit. It assumes that every noteOn has a corresponding noteOff event and it doesn't even bother with channel numbers. But I hope it helps to see how this could be done.

**Comment by stephaneeybert** [comment]
Thanks Chris. I had used the deltas, but to compute the absolute time of each event, then I checked to see if there was a tempo track and copied all tempo events into the other tracks, sorted by their absolute time so as to calculate the note durations by subtracting these times. My code seems to be more verbose than yours though :-) Thanks again !
