### ISSUE TITLE
Implementation of meta event with a type of "6"

### ISSUE THREAD

**Issue by maximedupre** [chrisguttandin/midi-json-parser#258]
Hello Chris!

Here is a file containing the meta event of type 6: https://ufile.io/fp70v

When parsing this file I get the following error:

    Error: Cannot parse a meta event with a type of "6"

Cheers!

**Comment by chrisguttandin** [comment]
Hi @maximedupre, can you please check that file with the latest version (in case you haven't done that already). Version 6.1 should be able to parse MarkerEvents.

**Comment by maximedupre** [comment]
Oh, I should've updated the package before opening a ticket :-). It works on v.6.1.

Thanks!

**Comment by chrisguttandin** [comment]
No worries, there are still some unimplemented events. Feel free to open another issue if you encounter one of those.
