### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by BopItFreak** [chrisguttandin/midi-json-parser#269]
I can't create json out of my midi file. 
here is my code: 
```
var fs = require("fs")
let b = fs.readFileSync('C:/Users/augus/Desktop/MIDI/mid/mapleaf.mid')
var ab = b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength);
var parseArrayBuffer = require("midi-json-parser")
parseArrayBuffer.parseArrayBuffer(ab)
    .then((json) => {
       midifile = json;
    });
```
and I get 
```
C:\Users\augus\node_modules\broker-factory\build\es5\bundle.js:136 Uncaught (in promise) Error: midiEvent is not defined
    at Worker.<anonymous> (C:\Users\augus\node_modules\broker-factory\build\es5\bundle.js:136)
```
[mapleaf.zip](https://github.com/chrisguttandin/midi-json-parser/files/3110082/mapleaf.zip)

how can I fix this? Midi file is attatched.

**Comment by chrisguttandin** [comment]
Hi @BopItFreak,

it looks like you are using Node.js. Unfortunately Node.js is not supported by this package. It is meant to run in the browser. It uses a WebWorker internally to run the code. Newer version of Node.js do support Workers as well, but the API and the concept are a bit different.

If using this package in the browser is not an option for you, you can maybe use the code which normally runs on the WebWorker directly. The actual `parseArrayBuffer()` function can be found here: https://github.com/chrisguttandin/midi-json-parser-worker/blob/ff00b13b074dc6d0edb9dcc605b029e9cf81f55f/src/midi-file-parser.ts#L31

I hope this helps.

**Comment by BopItFreak** [comment]
Thanks. I really appreciate you creating this module. midi-player-js in node has a lot of bugs, and there isn't really any other node midi module out there.

**Comment by chrisguttandin** [comment]
I'm glad it proves to be useful. But some MIDI events are still not implemented. Feel free to post files which don't work if you encounter any.

Did you get it to work by isolating the core code from the file that I linked?

**Comment by chrisguttandin** [comment]
Hi @BopItFreak, I'm closing this issue now. I hope you found a way to make use of this library.

Please feel free to open another issue in case you run into any other problems.
