### ISSUE TITLE
SyntaxError and ReferenceError

### ISSUE THREAD

**Issue by yuanchicai** [chrisguttandin/midi-json-parser#285]
1,import { encode } from 'json-midi-encoder' has an error :Uncaught SyntaxError: Unexpected token {

2,ReferenceError: Blob is not defined

**Comment by chrisguttandin** [comment]
Hi @yuanchicai,

from the very minimal description it is hard to tell which problem you ran into. But I think at least the second error looks like you are using the package with Node.js. This is unfortunately not supported. It only works in the browser.

But even when using it in the browser it needs to be used with a build process and can't be used directly. You can for example use webpack for that.

I hope this helps.

**Comment by chrisguttandin** [comment]
Hi @yuanchicai, I'm closing this issue now. Please feel free to reopen it or to open a new one instead.
