### ISSUE TITLE
Cannot parse a midi event with a type of "d"

### ISSUE THREAD

**Issue by ritz078** [chrisguttandin/midi-json-parser#303]
I am not able to parse a midi file. You can find the file (californication.mid) and demo at https://codesandbox.io/s/inspiring-mcnulty-vyx2n

The error in the console is 

<img width="1680" alt="Screenshot 2019-08-08 at 11 16 20 AM" src="https://user-images.githubusercontent.com/5389035/62678056-fb79ab80-b9cd-11e9-906d-94b003583ecd.png">

**Comment by ritz078** [comment]
Midi File: https://filebin.net/w33adr7sn4y4zfpq/californication.mid

**Comment by chrisguttandin** [comment]
Many thanks for reporting this. I just published version 6.4.0 which can parse the file.
