### ISSUE TITLE
Cannot parse a meta event with a type of "9"

### ISSUE THREAD

**Issue by ritz078** [chrisguttandin/midi-json-parser#304]
The MIDI (mario.mid) file and demo can be found at https://codesandbox.io/s/tender-merkle-kyewk

Since these events might keep coming, can we ignore this and just show them in the console as a warning rather than breaking the whole parsing?

File URL: https://bitmidi.com/uploads/98137.mid

**Comment by chrisguttandin** [comment]
Hi @ritz078,

many thanks for reporting this. The reason why this meta event wasn't supported up to now is because I had no example file which contained such an event. Many thanks for providing one.

It should work now with version 6.3.0. In case you're interested the actual fix is here: https://github.com/chrisguttandin/midi-json-parser-worker/commit/1391fe97cd8c1d548264630b082382395c2f5f04.

I know that it is annoying to encounter those errors but my hope was that by throwing those errors we can gather a rather complete set of test cases to cover as much MIDI event events as possible.

**Comment by ritz078** [comment]
> I know that it is annoying to encounter those errors but my hope was that by throwing those errors we can gather a rather complete set of test cases to cover as much MIDI event events as possible.

I understand this but this might break in production just because of a single unknown event. If this is a core feature of the website, I would like to process other events and neglect this one rather than breaking the whole website? A flag to disable that in production can also help. maybe take an option whether to throw or not which I can disable in prod.

**Comment by chrisguttandin** [comment]
Yes that's of course undesirable. But on the other hand I don't want to break the assumption that midi-json-parser and json-midi-encoder do at least preserve the meaning of a given file. Up to now this will work:

```js
import { encode } from 'json-midi-encoder';
import { parseArrayBuffer } from 'midi-json-parser';

const newArrayBuffer = await encode(await parseArrayBuffer(arrayBuffer));
// newArrayBuffer will have the same data as arrayBuffer expect for the running status encoding.
```

If we just ignore unknown events they will also miss in the re-encoded version of the MIDI file. One solution I could think of is to add unknown events similar to the [`UnknownTextEvent`](https://github.com/chrisguttandin/midi-json-parser-worker/blob/master/src/interfaces/midi-unknown-text-event.ts). The encoder can handle those events and can successfully encode them again.

Something that is on my todo list for a long time is to build a tool that downloads each MIDI file from BitMidi and then tries to parse it with midi-json-parser to see if it contains any unknown events. If you have time to build such a tool that would be super awesome. I have already asked BitMidi if they would be okay with it. https://twitter.com/BitMidi/status/1034537467209121792

**Comment by ritz078** [comment]
In case you need midi files, here's few that I guess BitMidi uses 
https://www.reddit.com/r/WeAreTheMusicMakers/comments/3ajwe4/the_largest_midi_collection_on_the_internet/

> Something that is on my todo list for a long time is to build a tool that downloads each MIDI file from BitMidi and then tries to parse it with midi-json-parser to see if it contains any unknown events. If you have time to build such a tool that would be super awesome. I have already asked BitMidi if they would be okay with it. https://twitter.com/BitMidi/status/1034537467209121792

I am no longer using midi-json-parser because sometimes a single track had the notes of different channels. So to make sure that didn't happen I had to create the JSON from scratch going through the programChange events. The code is [here](https://github.com/ritz078/raaga/blob/d87fcd3306491fdb1af3312bf8ac544752079baa/utils/MidiParser/MidiParser.ts#L121)

I will also need data from BitMidi so I will seek their permission. The product for which I will need that is live on https://synth-beta.now.sh/

**Comment by chrisguttandin** [comment]
Thanks for the pointer to the MIDI files.

That sounds very annoying that you have to traverse the MIDI files manually. I don't want to talk you into using midi-json-parser again. I'm just curious why you are using something different now? I think you could also manually alter the JSON produced by midi-json-parser or am I missing something? Anyway feel free to use whatever you want. This is not meant to be a sales talk. :-)

Your project looks very cool. I played with it for a little while. At some point I got a "Cannot read tracks of undefined" error but couldn't reproduce it.

Many thanks in advance. I would really appreciate to have a command line tool or something similar which can run a bulk test with a lot of files.

**Comment by ritz078** [comment]
Sorry for the delay in answering. Here's the reason https://twitter.com/ritz078/status/1164839790719590401 😄 

> That sounds very annoying that you have to traverse the MIDI files manually. I'm just curious why you are using something different now?

It wasn't due to the limitation of the library. I needed separate tracks for separate channels which play different instruments. directly grouping the track events based on channel id didn't seem to work so I had to write it myself.

For eg: https://bitmidi.com/uploads/88196.mid 
If I parse the above midi using this parser, I will get a single track having notes played by multiple instruments. Every parser available does the same. other than that this library is a perfect fit for my use case. Maybe I was doing something wrong.

I will be coming back to this library again after I release v1. This library also has a corresponding encoder that I need for recording.

> This is not meant to be a sales talk.
You don't even need one. This is most well-maintained midi parser on GitHub. A reason enough to prefer this over others

> Your project looks very cool. I played with it for a little while. At some point, I got a "Cannot read tracks of undefined" error but couldn't reproduce it.

This should be fixed now.

> Many thanks in advance. I would really appreciate having a command-line tool or something similar which can run a bulk test with a lot of files.

Really glad to be of help. I will let you know when it is ready. might take a while since I am currently busy with completing the initial version.

**Comment by chrisguttandin** [comment]
Thanks for your long response. And many thanks for typing it again. :-)

With this library I tried to parse the files as they are. midi-json-parser does not do any post processing which is probably what makes it so hard to use for your use case.

I agree that the layout of 88196.mid is confusing, I have no idea why the file uses several tracks which all send messages on channel 0.

**Comment by ritz078** [comment]
> Thanks for your long response. And many thanks for typing it again. :-)

That's the least I could do.

> With this library I tried to parse the files as they are. midi-json-parser does not do any post processing which is probably what makes it so hard to use for your use case.

Ya and that's why I did not open an issue as I don't think this library should handle it.

> I agree that the layout of 88196.mid is confusing, I have no idea why the file uses several tracks which all send messages on channel 0.

unfortunately, I have come across many such MIDI files.
